config/routes.rb
Rails.application.routes.draw do
  
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'    # Here we define the route, 'static_pages' is the controller name defined in 'app/controllers/concerns/static_pages_controller.rb'
                              # inside the controller we define an action in the form of a method 'home' , thus we reference the controller and its action as
                              # 'static_pages#home' , we pass this parameter to the roots method... 
                              # root("static_pages#home") 
  
  get  '/help',    to: 'static_pages#help'
  
  # It’s possible to use a named route other than the default using the as: option,you must also change the test file accordingly
  # get  '/help',    to: 'static_pages#help', as: 'helf'
  
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  
                                                                                # RESTful RESOURCES , they help in generating named routes for generating user URLs for various actions
                                                        
                                                          
                                                                                # ACTION      HTTP request         Named route                        Purpose
                                                                                # -------------------------------------------------------------------------------------------------------------------
  resources :users                                                              # index:          GET              users_path	                        => page to list all users
                                                                                # show:           GET              user_path(user)	                  => page to show user / user profile
                                                                                # new:            GET              new_user_path	                    => page to make a new user (signup)
                                                                                # create:         POST             users_path	                        => create a new user in the db after signup
                                                                                # edit:           GET              edit_user_path(user)	              => page to edit user with id 1
                                                                                # update:         PATCH	           user_path(user)	                  => when user update's user details
                                                                                # destroy         DELETE           destroy	user_path(user)	          => WHen a Admin user deletes other users
  
 
  resources :account_activations, only: [:edit]                                 # edit:           GET	             edit_account_activation_url(token) => when user signup's generate activation url

  
  resources :password_resets,     only: [:new, :create, :edit, :update]         # new:            GET              new_password_reset_path            => when user clicks on forgot password link 
                                                                                # create:         POST             password_resets_path               => create password reset link 
                                                                                # edit:           GET              edit_password_reset_url(token)     => when user tries to reset password using reset link
                                                                                # update:         PATCH            password_reset_path(token)         => when users tries to update wih new password
                                                                                
  resources :microposts,          only: [:create, :destroy]                     # create          POST	           microposts_path                    => when a user creates a new micropost
                                                                                # destroy         DELETE	         micropost_path(micropost)          => when a micropost is deleted by an user
  
  
  resources :relationships,       only: [:create, :destroy]                     # create          POST                                                => when user follows another user create a new relationship 
                                                                                #                                                                     => ( Creates a new record in the relationship table with [:follower_id, :followed_id]           
                                                                                # destroy         DELETE                                              => when user unfollows another user delete their corresponding relationship from the relationships table
  
  # The URLs for following and followers will look like 
  # /users/1/following and /users/1/followers. Since both
  # pages will be showing data, the proper HTTP verb is a GET request,
  # so we use the get method to arrange for the URLs to respond appropriately.
  # Meanwhile, the member method arranges for the routes 
  # to respond to URLs containing the user id.
  
  resources :users do                                                           # following       GET	        following	following_user_path(user_id)  => when user clicks on following a GET request 
                                                                                #                                                                        generates a page for That user listing all other
    member do     # For every user ID member 
                  # method arranges for the routes 
                  # to respond to URLs containing the user id.                  #                                                                        users he is following
      get :following, :followers                                                # followers       GET	        followers	followers_user_path(user_id)  => when user clicks on followers a GET request 
    end                                                                         #                                                                        generates a page for That user listing all his followers
  
  end                                                                           


  resources :microposts do
    resources :likes
    resources :dislikes
    resources :hearts
    end
  
   
  
end

# _path helpers provide a site-root-relative path. You should probably use this most of the time. Eg: /password_resets

# _url helpers provide an absolute path, including protocol and server name. Eg: http://ex.co/password_resets/<token>/edit

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
    if logged_in?
      @micropost = current_user.microposts.build if logged_in?        # current_user exists only if the user is logged in, so the @micropost variable should only be defined in this case.
      @feed_items = current_user.feed.paginate(page: params[:page])   # @feed_items instance variable for the current user’s (paginated) feed
    end
  end


  def help
  end
  
  def about
  end
  
  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_logged_in_home.html.erb
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>       <!-- display user ifo: image and name -->
      </section>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
      <section class="micropost_form">       
        <%= render 'shared/micropost_form' %>  <!-- display form to create micropost's -->
      </section>
    </aside>
    <div class="col-md-8">
      <h3>Micropost Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>

app/views/static_pages/_logged_out_home.html.erb
<div class="center jumbotron">
    <h1 id="welcome">Welcome to Socially...</h1>

    <h3 id="welcome-text">
      Connect with your friends and socialize easily with Socially, signup to begin...
    </h3>

    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p class="general general-center">
   Hello ! I am Arpan, the creater of Socially. Socially is a hobby project maintained by me.
   The webiste is build using Ruby on Rails and is based on the sample app in 
   The <a href="https://www.railstutorial.org/"><em>Ruby on Rails
   Tutorial</em></a> by Michael Hartl.
</p>
<p class="general general-center">
  Connect with me here...
</p>
<div class="icon-box general-center">
    <a href="https://github.com/Arp-G" target="_blank" title="Github"><i class="devicon-github-plain colored"></i></a>
    <a href="https://www.linkedin.com/in/arpan-ghoshal-063665142/" target="_blank" title="Linkedin"><i class='fab fa-linkedin'></i></a>
    <a href="https://www.facebook.com/ArpRokzz" target="_blank" title="Github"><i class='fab fa-facebook'></i></a>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<div class="general general-center">
<p>
  For any query email me at <a href="mailto:name@email.com">arpanghoshal3@gmail.com</a>
</p>
  
<p class="general general-center">
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="https://www.railstutorial.org/contact">contact page</a>.
</p>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p class="general general-center">
  For any bugs contact me at <a href="mailto:name@email.com">arpanghoshal3@gmail.com</a>
</p>

<p class="general general-center">
  Or reach out ot me at...
</p>

<div class="icon-box general-center">
    <a href="https://github.com/Arp-G" target="_blank" title="Github"><i class="devicon-github-plain colored"></i></a>
    <a href="https://www.linkedin.com/in/arpan-ghoshal-063665142/" target="_blank" title="Linkedin"><i class='fab fa-linkedin'></i></a>
    <a href="https://www.facebook.com/ArpRokzz" target="_blank" title="Github"><i class='fab fa-facebook'></i></a>
</div>

app/views/static_pages/home.html.erb
<% if logged_in? %>                                         <!-- Display form allowing user to create micropost on home page only if user is logged in -->
  <%= render 'static_pages/logged_in_home' %>               <!-- Renders the partial _logged_in_home.html.erb containing code to show create micropost form and user info -->
<% else %>
  <%= render 'static_pages/logged_out_home' %>              <!-- Renders the partial _logged_out_home.html.erb containing code to show signup now option -->
<% end %>
            
            
            
            
            
            
            
            